
steps:
  -name: Gerar artefato ZIP
  run: zip -r pipeline-demo.zip .


  -name: Publicar artefato
  uses: actions/upload-artifact@v3
    with:
      name: codigo-buildado
      path: pipeline-demo.zip 